server:
  port: 6001
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sample_order?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

transactiond:
  client:
    managerAddress:
      - 192.168.0.1:6102
      - 192.168.0.2:6102
      - 192.168.0.3:6102